-- MySQL Script generated by MySQL Workbench
-- Thứ tư, 29 Tháng 11 Năm 2023 22:41:34 +07
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ha
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ha
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ha` ;
USE `ha` ;

-- -----------------------------------------------------
-- Table `ha`.`user_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ha`.`user_login` (
  `user_id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(100) NOT NULL,
  `user_password` VARCHAR(100) NOT NULL,
  `user_session_id` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `idx_user_login_user_id` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6;


-- -----------------------------------------------------
-- Table `ha`.`user_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ha`.`user_post` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL DEFAULT NULL,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `type` INT(11) NULL DEFAULT NULL,
  `score` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  CONSTRAINT `fk_user_post_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `ha`.`user_login` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
